# -*- coding: utf-8 -*-
"""waspas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8gj6ur6VOPso3y7xiFCdVxiMcr9tttq
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="SPK WASPAS", layout="wide")
st.title("🔎 Sistem Pendukung Keputusan Penentuan Bonus Akhir Tahun Outward Bound Indonesia - Metode WASPAS")

# -----------------------------
# Fungsi WASPAS
# -----------------------------
def waspas(df_values, weights, impacts, lamb=0.5):
    X = df_values.copy().astype(float)
    m, n = X.shape

    w = np.array(weights, dtype=float)
    if not np.isclose(w.sum(), 1.0):
        w = w / w.sum()

    R = np.zeros_like(X.values)
    for j, col in enumerate(X.columns):
        colvals = X.iloc[:, j].values.astype(float)
        if impacts[j] == "Benefit":
            denom = colvals.max()
            R[:, j] = colvals / denom if denom != 0 else 0
        else:
            denom = colvals.min()
            R[:, j] = denom / colvals
            R[:, j] = np.nan_to_num(R[:, j], nan=0, posinf=0, neginf=0)

    # WSM
    Q1 = R.dot(w)

    # WPM
    Q2 = np.ones(m)
    for i in range(m):
        prod = 1
        for j in range(n):
            r = R[i, j]
            if r == 0 and w[j] > 0:
                prod = 0
                break
            prod *= r ** w[j]
        Q2[i] = prod

    # WASPAS final
    Q = lamb * Q1 + (1 - lamb) * Q2

    result = pd.DataFrame({
        'Q1_WSM': Q1,
        'Q2_WPM': Q2,
        'Q_WASPAS': Q
    }, index=df_values.index)

    result["Rank"] = result["Q_WASPAS"].rank(ascending=False, method="min").astype(int)
    result = result.sort_values("Rank")

    return result


# -----------------------------------
# Input jumlah kriteria dan alternatif
# -----------------------------------
st.subheader("⚙️ Input Parameter SPK")

col1, col2 = st.columns(2)

with col1:
    jml_kriteria = st.number_input("Jumlah Kriteria", min_value=1, max_value=20, value=3)
with col2:
    jml_alternatif = st.number_input("Jumlah Alternatif", min_value=1, max_value=50, value=3)


# -----------------------------
# Input detail kriteria
# -----------------------------
st.subheader("📌 Input Kriteria")

kriteria_names = []
weights = []
impacts = []

for i in range(jml_kriteria):
    c1, c2, c3 = st.columns(3)
    with c1:
        nama = st.text_input(f"Nama Kriteria {i+1}", value=f"C{i+1}")
    with c2:
        bobot = st.number_input(f"Bobot K{i+1}", min_value=0.0, value=1.0)
    with c3:
        tipe = st.selectbox(f"Tipe K{i+1}", ["Benefit", "Cost"])

    kriteria_names.append(nama)
    weights.append(bobot)
    impacts.append(tipe)


# -----------------------------
# Input alternatif + nilai
# -----------------------------
st.subheader("📋 Input Alternatif & Nilai Matriks Keputusan")

data = {}
alt_names = []

for a in range(jml_alternatif):
    st.markdown(f"### ➤ Alternatif {a+1}")
    alt_name = st.text_input(f"Nama Alternatif {a+1}", value=f"A{a+1}")
    alt_names.append(alt_name)

    nilai_alt = []
    c_cols = st.columns(jml_kriteria)
    for k in range(jml_kriteria):
        nilai = c_cols[k].number_input(
            f"{kriteria_names[k]} ({alt_name})",
            value=0.0
        )
        nilai_alt.append(nilai)

    data[alt_name] = nilai_alt

# Buat DataFrame keputusan
df = pd.DataFrame(data, index=kriteria_names).T

st.write("### 📊 Matriks Keputusan")
st.dataframe(df)


# -----------------------------
# Input λ WASPAS
# -----------------------------



# -----------------------------
# Tombol Proses
# -----------------------------
if st.button("🚀 Proses WASPAS"):
    result = waspas(df, weights, impacts, lamb)
    st.subheader("🏆 Hasil Perhitungan WASPAS")
    st.dataframe(result)

    winner = result.index[0]
    st.success(f"Alternatif terbaik adalah **{winner}** berdasarkan nilai WASPAS tertinggi.")
